### ISSUE TITLE
Error starting Daemon

### ISSUE THREAD

**Issue by Kevin-Luke** [juaneth/Omnipetal-Daemon#1]
Receiving this when I try to start the daemon using the commands given in the documentation:

0|index    | }
0|index    | TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
0|index    |     at Object.writeFileSync (node:fs:2163:5)
0|index    |     at /home/kevin/Documents/Code/github/Omnipetal-Daemon/passkeys.js:7:16
0|index    |     at /home/kevin/Documents/Code/github/Omnipetal-Daemon/node_modules/bcrypt/bcrypt.js:139:13
0|index    |     at processTicksAndRejections (node:internal/process/task_queues:78:11) {
0|index    |   code: 'ERR_INVALID_ARG_TYPE'
0|index    | }
0|index    | TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
0|index    |     at Object.writeFileSync (node:fs:2163:5)
0|index    |     at /home/kevin/Documents/Code/github/Omnipetal-Daemon/passkeys.js:7:16
0|index    |     at /home/kevin/Documents/Code/github/Omnipetal-Daemon/node_modules/bcrypt/bcrypt.js:139:13
0|index    |     at processTicksAndRejections (node:internal/process/task_queues:78:11) {
0|index    |   code: 'ERR_INVALID_ARG_TYPE'
0|index    | }

I'm on ubuntu 20

**Comment by FinlayDaG33k** [comment]
Start the daemon with `pm2 start index.js -- lamepassword` first (where "lamepassword" obviously isn't a lame password).
This will set the daemon passkey.

**Comment by juaneth** [comment]
uhh fixed but this guy was right, it was adebug thing i left to temporarily set the passkeys but forgot ab and then yh 👍🏼
